### ISSUE TITLE
Symbolic link infinite loop

### ISSUE THREAD

**Issue by glepore70** [Georgetown-University-Libraries/File-Analyzer#52]
Running the File-Analyzer in File List mode on a Linux system with symbolic links can produce an infinite loop. Suggest:

Files.isSymbolicLink(target) //here target is a path.

to check for symbolic links.

**Comment by terrywbrady** [comment]
@glepore70, thanks for alerting me to this.  I will investigate this.

**Comment by terrywbrady** [comment]
@glepore70, I did some quick testing on a linux server with a very simple structure and I did not encounter the infinite loop.  (I did not deliberately create one either.)  Can you send me more details of your test directory structure and I will brainstorm a solution?

**Comment by glepore70** [comment]
Hmm. I deliberately created one after encountering it on a large directory structure.

![loop](https://cloud.githubusercontent.com/assets/1309562/9134269/8e6a10c6-3cd0-11e5-9e6c-709d304c98da.jpg)

However, without seeing the loop in any output I can't say for sure that the infinite loop occurred on the large directory.

I'm sure it occurs, but whether or not my computer is an anomaly or not I can't say. I do have a lot of symbolic links to various directories and hard drives.

It probably still makes sense to add some code to detect infinite loops.

**Comment by terrywbrady** [comment]
Thanks.  Here are my current thoughts
* Create a Set/Map of every fully resolved path that has been visited
* Once a path has been visited, skip it in the future (whether a file or a directory)
* On systems without symlinks, do not track visited paths

**Comment by glepore70** [comment]
That was basically my thought, record every path once and check it later. There is the Files.isSymbolicLink command which I think takes care of most of that for you. In our code it's just a couple of lines.

**Comment by terrywbrady** [comment]
@glepore70, The FileAnalyzer stops after processing a maximum number of files, so that is how the infinite loop was avoided during your test.

I have a quick initial solution to disable symlink traversal:

https://github.com/Georgetown-University-Libraries/File-Analyzer/pull/53

I will add more logic to visit a file only once (if symlinks are enabled).

**Comment by terrywbrady** [comment]
https://github.com/Georgetown-University-Libraries/File-Analyzer/pull/53 closed and deployed as a release https://github.com/Georgetown-University-Libraries/File-Analyzer/releases/tag/v4.0.2
